---
version: '3.3'
networks:
    gocd:
        driver: bridge
volumes:
    server-data:
    server-home:
    agent-data:
    agent-home:
services:
    server:
        container_name: gocd-server
        image: gocd/gocd-server:v18.12.0
        volumes:
            - server-data:/godata
            - server-home:/home/go
        networks:
            - gocd
        ports:
            - 8153:8153
            - 8154:8154
    agent:
        container_name: gocd-agent
        image: custom/gocd-agent:latest
        build:
            context: .
            dockerfile: agent-ubuntu.Dockerfile
        depends_on:
            - server
        environment:
            GO_SERVER_URL: "https://server:8154/go"
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        volumes:
            - agent-data:/godata
            - agent-home:/home/go
        networks:
            - gocd
        ports:
            - 8152:8152
