---
version: '3.3'
networks:
    teamcity:
        driver: bridge
volumes:
    teamcity-data:
    teamcity-logs:
    teamcity-agent:
services:
    server:
        container_name: teamcity-server
        build:
            context: .
            dockerfile: Dockerfile.teamcity-server
        volumes:
            - teamcity-data:/data/teamcity_server/datadir
            - teamcity-logs:/opt/teamcity/logs
        networks:
            - teamcity
        ports:
            - 8111:8111
    agent:
        container_name: teamcity-agent
        build:
            context: .
            dockerfile: Dockerfile.teamcity-agent
        volumes:
            - teamcity-agent:/data/teamcity_agent/conf
        networks:
            - teamcity
        environment:
            - SERVER_URL=http://teamcity-server:8111
